---

dist: bionic

language: python
python:
  - 3.6

env:
  global:
    - ROLE_NAME: gcc
  matrix:
    - MOLECULE_DISTRO: ubuntu1804

install:
  - pip install molecule[lxd] ansible-lint flake8

before_script:
  - ansible-galaxy install teebor_choka.lxd
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
  - molecule lint

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
