---

- name: establish build prerequisites
  become: true
  package:
    name: "{{ compiler_needed_tools + ['wget','tar'] }}"
    state: present

- name: prepare paths
  set_fact:
    source_path: "{{ gcc_dir + '/gcc-' + gcc_version }}"
    build_dir_path: "{{ gcc_dir + '/gcc-' + gcc_version + '/build/' }}"

- name: establish repo dir
  file:
    path: "{{ gcc_dir }}"
    recurse: true
    state: directory

- name: extract source tarball
  become: true
  unarchive:
    src: "https://ftp.gnu.org/gnu/gcc/gcc-{{ gcc_version }}/gcc-{{ gcc_version }}.tar.gz"
    remote_src: true
    dest: "{{ gcc_dir }}"

- name: download prerequisites
  command: "./contrib/download_prerequisites"
  args:
    chdir: "{{ source_path }}"
    creates: "{{ source_path }}/gmp-4.3.2.tar.bz2"

- name: ensure build directory existence
  become: true
  file:
    path: "{{ build_dir_path }}"
    state: directory

- name: configure build process
  command: "{{ source_path }}/configure {{ compiler_args | join(' ') }}"
  args:
    chdir: "{{ build_dir_path }}"
  changed_when: false

- name: build
  make:
    chdir: "{{ build_dir_path }}"
    target: all
    params:
      --jobs: "{{ ansible_processor_cores * ansible_processor_threads_per_core }}"

- name: install
  when: gcc_install | bool
  make:
    chdir: "{{ build_dir_path }}"
    target: install
