---

- name: load platform specific variables
  include_vars: "{{ item }}"
  loop: "{{ query('first_found', params, errors='ignore') }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
      paths:
        - '{{ role_path }}/vars'

- name: ensure gcc repo presence
  when: ansible_os_family == 'Debian'
  become: true
  apt_repository:
    repo: ppa:ubuntu-toolchain-r/test
    state: present

- name: build and install the GCC
  vars:
    compiler_args: "{{ compiler_default_args + (gcc_build_args | default([])) }}"
  block:
    - name: check prefix existence
      stat:
        path: "{{ compiler_args | select('search', '--prefix=.*') | map('regex_replace','^--prefix=(?P<prefix>.+)$', '\\g<prefix>') | list | last }}/bin"
      register: prefix_path
      changed_when: false

    - include_tasks: build_from_source.yml
      when: not prefix_path.stat.exists
