---

- include_tasks: "{{ compiler_collection.key }}.yml"
  vars:
    detail: "{{ compiler_collection.value }}"
  loop_control:
    loop_var: compiler_collection
  with_dict: "{{ compilers }}"
  when: compilers is defined
