---

- name: load prerequisite tasks
  # include_tasks: "{{ lookup('first_found', params, errors='ignore') }}"
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
      paths:
        - '{{ role_path }}/tasks/prerequisites/'
      skip: true

- name: establish package
  become: yes
  package:
    name: gcc
    state: present

- block:
    - include_tasks: from_source_code.yml 

    - become: yes
      package:
        name: gcc
        state: absent
  when:
    - source is defined


